### ISSUE TITLE
Restrict command to `grunt happyplan:*`?

### ISSUE THREAD

**Issue by MoOx** [happyplan/happyplan-cli#1]
Since latest modifications, [you can see](https://github.com/happyplan/happyplan-cli/blob/master/bin/happyplan#L26) that we can run all grunt tasks (happyplan is just a "wrapper"). Maybe it's a good idea to restrict to custom happyplan tasks to avoid freestyle call outside the appropriate happyplan context ?
Doing that, we can prefix all happyplan tasks using `happyplan:`. What do you thing @kud ?

**Comment by kud** [comment]
Maybe we should indeed (re)name all public methods with `happyplan:*` and the wrapper only displays/lists `happyplan:*` commands.

**Comment by MoOx** [comment]
That's the idea !

**Comment by kud** [comment]
:heavy_check_mark:

**Comment by MoOx** [comment]
Closed by 0.2.0 https://github.com/happyplan/happyplan-cli/commit/86833e7b0f688017c7c47d44fb643cdfd73093e2
